name: Build PHP binaries

on:
  push:
    branches: "**"
    tags-ignore: "php-**"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    name: Linux (PM ${{ matrix.pm-version-major }})
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        pm-version-major: [4]

    steps:
      - uses: actions/checkout@v3

      - name: Install tools and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make autoconf automake libtool libtool-bin m4 wget libc-bin gzip bzip2 bison g++ git re2c

      - name: Prepare compile.sh download cache
        id: download-cache
        uses: actions/cache@v3
        with:
          path: ./download_cache
          key: compile-sh-cache-ssl-https-${{ hashFiles('./compile.sh') }}
          restore-keys: compile-sh-cache-ssl-https-

      - name: Compile PHP
        run: |
          # Used "set -ex" instead of hashbang since script isn't executed with hashbang
          set -ex
          trap "exit 1" ERR
          ./compile.sh -t linux64 -j 4 -g

      - name: Create tarball
        run: |
          tar -czf ./PHP-Linux-x86_64-PM${{ matrix.pm-version-major }}.tar.gz bin
          tar -czf ./PHP-Linux-x86_64-PM${{ matrix.pm-version-major }}-debugging-symbols.tar.gz bin-debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Linux-PM${{ matrix.pm-version-major }}
          path: |
            ./PHP-Linux-x86_64-PM${{ matrix.pm-version-major }}*.tar.gz
            install.log
            compile.sh
          if-no-files-found: error

      - name: Prepare workspace for upload
        if: failure()
        run: tar -czf workspace.tar.gz install_data

      - name: Upload workspace
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Linux-workspace-PM${{ matrix.pm-version-major }}
          path: |
            workspace.tar.gz
          if-no-files-found: error
