name: Build PHP binaries

on:
  push:
    branches: "**"
    tags-ignore: "php-**"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  windows:
    name: Windows (PM ${{ matrix.pm-version-major }})
    runs-on: windows-2019
    strategy:
      matrix:
        pm-version-major: [ 4 ]

    steps:
      - uses: actions/checkout@v3
      
      - name: Install tools and dependencies
        run: choco install wget --no-progress
        
      - name: Compile PHP
        run: .\windows-compile-vs.bat
        env:
          VS_EDITION: Enterprise
          SOURCES_PATH: ${{ github.workspace }}\pocketmine-php-sdk
          PM_VERSION_MAJOR: ${{ matrix.pm-version-major }}

      - name: Rename artifacts
        run: |
          mkdir temp
          move php-debug-pack-*.zip temp/PHP-Windows-x64-PM${{ matrix.pm-version-major }}-debugging-symbols.zip
          move php-*.zip temp/PHP-Windows-x64-PM${{ matrix.pm-version-major }}.zip
          move temp\*.zip .

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Windows-PM${{ matrix.pm-version-major }}
          path: |
            PHP-Windows-x64*.zip
            compile.log
            windows-compile-vs.bat
          if-no-files-found: error
